import test from 'node:test'
import assert from 'node:assert/strict'
import { initialState } from '../src/lib/catalogue.ts'
import { earnedCredits, completedCodes, groupProgress, repeatingCodes, moveWarnings, plannedCredits, validateState, type Enrollment } from '../src/lib/model.ts'
import { parseKosPdf, parseJsonImport, mergeImport, type PdfItem } from '../src/lib/imports.ts'
function enrollment(code:string,semester:string,grade:string,credits:number,completion='Z,ZK',assessment='Z'):Enrollment{return {id:`${semester}:${code}`,code,semester,grade,credits,completion,assessment,role:'P',date:'',teacher:'',source:'synthetic test'}}
test('Repeated failures never double count earned credits; zero-credit requirements still complete',()=>{const s=initialState();s.enrollments=[enrollment('B2B31ZEOA','B242','F',5),enrollment('B2B31ZEOA','B252','E',5),enrollment('B0B04B1K','B241','A',0,'KZ',''),enrollment('B3B02FY2','B251','',6,'Z,ZK','N')];assert.equal(earnedCredits(s),5);assert.equal(completedCodes(s).size,2);assert.deepEqual([...repeatingCodes(s)],['B3B02FY2']);assert.equal(groupProgress(s).find(g=>g.id==='english')?.passedCount,1)})
test('Historical group credits use enrollment snapshot and are deterministic',()=>{const s=initialState();s.enrollments=[enrollment('B0B01LAGA','B251','B',7),enrollment('B0B01LAGA','B241','C',6)];s.courses.find(c=>c.code==='B0B01LAGA')!.credits=8;assert.equal(earnedCredits(s),7);assert.equal(groupProgress(s)[0].earned,7);s.enrollments.reverse();assert.equal(earnedCredits(s),7)})
test('Programming and introductory PV do not satisfy professional PV',()=>{const s=initialState();s.enrollments=[enrollment('BAB37ZPR','B241','A',6),enrollment('BAB31UBI','B241','B',4),enrollment('B3B38LPE','B252','C',4)];const groups=groupProgress(s);assert.equal(groups.find(g=>g.id==='electiveCore')?.earned,4);assert.equal(groups.find(g=>g.id==='programming')?.earned,6)})
test('Warnings cover term mismatch, thesis semester, KOS enrollment and work budget',()=>{const s=initialState();assert.match(moveWarnings(s,'B3B02FY2','B262').join(' '),/jen v zimě/);assert.match(moveWarnings(s,'B0B01STP','B272').join(' '),/Poslední semestr/);s.enrollments=[enrollment('BAB31GEN','B261','',3,'ZK','')];assert.match(moveWarnings(s,'BAB31GEN','B271').join(' '),/zapsaný v KOSu/);s.settings.weekBudget=20;assert.match(moveWarnings(s,'B0B01LAGA','B261').join(' '),/nad rozpočtem/);assert.deepEqual(moveWarnings(s,'B0B01LAGA',null),[])})
test('Legacy migration accepts KOS URLs, merges duplicates and preserves planned placement',()=>{const subject={name:'STP',code:'https://kos.cvut.cz/course-syllabus/B0B01STP/B252',credits:5,type:'P',semesterId:2};const p=parseJsonImport(JSON.stringify({subjects:[subject,{...subject,code:'B0B01STP',semesterId:null}],semesterCount:4}));assert.equal(p.courses.length,1);assert.equal(p.placements?.B0B01STP,'B262');const s=mergeImport(initialState(),p);assert.equal(plannedCredits(s),5);assert.equal(s.courses.find(c=>c.code==='B0B01STP')?.season,'summer')})
const headers=['Kód','Název','Kr','Zak','Záp.','Dat.záp.','Záp.udělil','Zn.','Dat.zn.','Zn.udělil','Uzav.'];const xs=[57,99,245,261,281,298,340,395,414,456,510];function line(values:string[],y:number):PdfItem[]{return values.flatMap((str,i)=>str?[{str,x:xs[i],y}]:[])}
function pdf(grade='C',summary=7){return [{items:[{str:`Získáno kreditů: ${summary}`,x:57,y:700},{str:'Semestr: B241',x:57,y:650},...line(headers,630),...line(['B0B01LAGA','Lineární algebra','7','Z,ZK','Z','','',grade,'','','A'],610),...line(['B0B04B1K','Anglický jazyk B1','0','KZ','Z','','','A','','','A'],590)]}]}
test('PDF parser reads positional grade separately from closed-column A and zero credits',()=>{const p=parseKosPdf(pdf());assert.equal(p.enrollments[0].grade,'C');assert.equal(p.enrollments[1].credits,0);assert.equal(p.enrollments.length,2);assert.throws(()=>parseKosPdf(pdf('F',7)),/Kontrola nesouhlasí/);const p2=parseKosPdf(pdf('F',0));assert.equal(p2.enrollments[0].grade,'F')})
test('PDF parser preserves wrapped names',()=>{const p=pdf();p[0].items.push({str:'pokračování názvu',x:99,y:602});const parsed=parseKosPdf(p);assert.equal(parsed.courses[0].name,'Lineární algebra pokračování názvu')})
test('Full PDF snapshot replaces removed results and repeated import is idempotent',()=>{const first=parseKosPdf(pdf());let s=mergeImport(initialState(),first);s=mergeImport(s,first);assert.equal(s.enrollments.length,2);s.plans[0].placements.BBAP20='B272';const corrected=parseKosPdf(pdf('F',0));s=mergeImport(s,corrected);assert.equal(earnedCredits(s),0);assert.equal(s.plans[0].placements.BBAP20,'B272')})
test('Invalid backup and unsupported files fail without touching the input state',()=>{const s=initialState();const before=JSON.stringify(s);assert.throws(()=>parseJsonImport('{bad'));assert.throws(()=>parseJsonImport(JSON.stringify({...s,settings:{...s.settings,name:42}})));assert.throws(()=>parseJsonImport(JSON.stringify({subjects:[{name:'Invalid',code:'X1',credits:-1,type:'P'}],semesterCount:4})));const bad=structuredClone(s);bad.plans[0].placements.BBAP20='B999';assert.throws(()=>validateState(bad));assert.equal(JSON.stringify(s),before)})
test('Full backup round trip retains all state and strips unsafe outbound links',()=>{const s=initialState();s.courses[0].kosLink='javascript:alert(1)';const p=parseJsonImport(JSON.stringify(s));assert.equal(p.backup?.courses[0].kosLink,'');assert.equal(p.backup?.settings.workHours,20)})
