import { CATALOGUE } from './catalogue.ts'
import { cleanCode, earnedCredits, isPassed, safeUrl, SEMESTERS, validateState, type Course, type Enrollment, type Role, type StudyState } from './model.ts'
export interface PdfItem {str:string;x:number;y:number}
export interface ImportPreview {kind:'results'|'legacy'|'backup';courses:Course[];enrollments:Enrollment[];official?:StudyState['official'];placements?:Record<string,string|null>;backup?:StudyState;notes:string[];source:string}
const extraRoles:Record<string,Role>={BEZB:'P',BEZZ:'P'}
function unknownCourse(code:string,name:string,credits:number):Course{return {code,name,credits,role:extraRoles[code]||'V',season:'unknown',group:'other',lectures:0,practices:0,labs:0,selfStudy:null,hoursKnown:false,kosLink:`https://kos.cvut.cz/course-syllabus/${encodeURIComponent(code)}`,surveyLink:''}}
function pdfLines(items:PdfItem[]){const lines:{y:number;items:PdfItem[]}[]=[];for(const it of items.filter(i=>i.str.trim()).sort((a,b)=>b.y-a.y||a.x-b.x)){const line=lines.find(l=>Math.abs(l.y-it.y)<2);if(line)line.items.push(it);else lines.push({y:it.y,items:[it]})}return lines.map(l=>l.items.sort((a,b)=>a.x-b.x))}
export function parseKosPdf(pages:{items:PdfItem[]}[],source='Výpis KOS (PDF)'):ImportPreview {
 const enrollments:Enrollment[]=[],courses:Course[]=[];let semester='',lastCode='',headers:PdfItem[]=[];const official:StudyState['official']={credits:null,average:null,weightedAverage:null,importedAt:new Date().toISOString(),source};const notes:string[]=[]
 for(const page of pages){for(const line of pdfLines(page.items)){const text=line.map(i=>i.str).join(' ').replace(/\u200b/g,'');const sem=text.match(/Semestr:\s*(B\d{2}[12])/i);if(sem){semester=sem[1];lastCode='';continue}for(const [pattern,key] of [[/Získáno kreditů:\s*(\d+)/i,'credits'],[/Aritmetický průměr:\s*([\d,.]+)/i,'average'],[/Vážený průměr:\s*([\d,.]+)/i,'weightedAverage']] as const){const m=text.match(pattern);if(m)official[key]=Number(m[1].replace(',','.'))}
 if(line.some(i=>i.str==='Kód')&&line.some(i=>i.str==='Název')){headers=line;continue}
 if(!semester||!headers.length)continue;const first=line[0]?.str.trim();if(!first||!/^[A-Z0-9][A-Z0-9-]{2,19}$/.test(first)){const nameX=headers.find(h=>h.str==='Název')?.x,creditX=headers.find(h=>h.str==='Kr')?.x;if(lastCode&&nameX!==undefined&&creditX!==undefined&&line.every(i=>i.x>=nameX-2&&i.x<creditX-4)){const previous=courses.find(c=>c.code===lastCode);if(previous)previous.name+=' '+text.trim()}continue}
 const values:Record<string,string>={};for(const item of line){const header=[...headers].reverse().find(h=>item.x>=h.x-4);if(header)values[header.str]=(values[header.str]?values[header.str]+' ':'')+item.str}
 const code=values['Kód']?.trim(),name=values['Název']?.trim(),credits=Number(values.Kr);if(!code||!name||!values.Kr||!Number.isFinite(credits))throw new Error(`Nečitelný řádek ${first}. Použij český PDF výpis přímo z KOSu.`)
 const known=CATALOGUE.find(c=>c.code===code);const course={...(known||unknownCourse(code,name,credits)),name,credits};if(!courses.some(c=>c.code===code))courses.push(course)
 const completion=(values.Zak||'').replace(/\s/g,''),grade=(values['Zn.']||'').trim(),assessment=(values['Záp.']||'').trim();if(!['Z','KZ','ZK','Z,ZK'].includes(completion)||!['','A','B','C','D','E','F'].includes(grade)||!['','Z','N'].includes(assessment))throw new Error(`Nerozpoznané hodnocení u ${code}. Import byl zastaven, aby se neuložily chybné výsledky.`)
 lastCode=code;enrollments.push({id:`${semester}:${code}`,code,semester,credits,role:course.role,completion,assessment,grade,date:values['Dat.zn.']||values['Dat.záp.']||'',teacher:values['Zn.udělil']||values['Záp.udělil']||'',source})
 }}
 if(!enrollments.length)throw new Error('Ve výpisu nejsou čitelné studijní výsledky. Použij KOS → Studium → Studijní výsledky → Tisk → Česky. Naskenované PDF není podporováno.')
 const done=new Map<string,number>();enrollments.filter(isPassed).forEach(e=>done.set(e.code,e.credits));const total=[...done.values()].reduce((n,c)=>n+c,0);if(official.credits!==null&&official.credits!==total)throw new Error(`Kontrola nesouhlasí: KOS uvádí ${official.credits} kreditů, řádky dávají ${total}. Data se neuložila.`)
 if(new Set(enrollments.map(e=>e.id)).size!==enrollments.length)throw new Error('Výpis obsahuje duplicitní řádky pro stejný semestr. Zkontroluj export.')
 if(official.credits===null)notes.push('Výpis neobsahuje souhrn kreditů. Součet zkontroluj v náhledu.')
 notes.push('Úplný výpis aktualizuje historii studia. Zápisy, které v novém výpisu nejsou, se z historie odstraní. Plány a poznámky zůstanou.')
 notes.push('PDF neobsahuje roli P/PV/V. Pro známé předměty se použije katalog BIO 2018; ostatní lze upravit v detailu.')
 return {kind:'results',courses,enrollments,official,notes,source}
}
export function parseJsonImport(text:string):ImportPreview {let data:unknown;try{data=JSON.parse(text)}catch{throw new Error('Soubor není platný JSON.')}const d=data as Record<string,unknown>;if(d?.schemaVersion===2){const backup=validateState(data);return {kind:'backup',courses:backup.courses,enrollments:backup.enrollments,backup,notes:['Obnovení zálohy nahradí všechny výsledky, plány a nastavení v tomto prohlížeči.'],source:'Záloha Semester V2'}}
 if(!d||!Array.isArray(d.subjects))throw new Error('Podporujeme zálohu V2 nebo JSON export z původního Semester Planneru.')
 if(d.subjects.length>3000||!Number.isInteger(d.semesterCount)||Number(d.semesterCount)<1||Number(d.semesterCount)>50)throw new Error('Neplatný počet semestrů nebo předmětů ve V1.')
 const courses:Course[]=[],placements:Record<string,string|null>={},notes:string[]=[];for(const raw of d.subjects){const v=raw as Record<string,unknown>;if(typeof v.code!=='string'||typeof v.name!=='string'||!v.name.trim())throw new Error('Předmět ve V1 nemá název nebo kód.');const code=cleanCode(v.code);if(!/^[A-Z0-9][A-Z0-9-]{1,29}$/.test(code))throw new Error(`Nerozpoznaný kód: ${code}. Oprav ho ve V1 nebo v JSON souboru.`);const credits=Number(v.credits);if(!Number.isFinite(credits)||credits<0||credits>999||!['P','PV','V'].includes(String(v.type)))throw new Error(`Neplatné údaje předmětu ${code}.`);const known=CATALOGUE.find(c=>c.code===code),hours=(k:string)=>{const n=Number(v[k]??0);if(!Number.isFinite(n)||n<0||n>168)throw new Error(`Neplatné hodiny u ${code}.`);return n};const course:Course={...(known||unknownCourse(code,v.name,credits)),name:known?.name||v.name,credits,role:known?.role||(v.type as Role),season:known?.season||(['winter','summer','both'].includes(String(v.season))?v.season as Course['season']:'unknown'),lectures:hours('lectures'),practices:hours('practices'),labs:hours('labs'),selfStudy:hours('selfStudy')||null,hoursKnown:true,kosLink:safeUrl(String(v.kosLink||'')),surveyLink:safeUrl(String(v.surveyLink||''))};const existing=courses.find(c=>c.code===code);if(existing)notes.push(`${code}: duplicitní předmět byl sloučen.`);else courses.push(course);const sem=v.semesterId;if(sem!==null&&sem!==undefined){if(!Number.isInteger(sem)||Number(sem)<1)throw new Error(`Neplatný semestr u ${code}.`);if(Number(sem)<=4)placements[code]=SEMESTERS[Number(sem)-1].id;else notes.push(`${code}: semestr mimo čtyřsemestrální plán; předmět zůstane nezařazený.`)}else if(!(code in placements))placements[code]=null}
 notes.push('Semestry V1 1–4 se převedou na zimu 2026 až léto 2028. Hotové předměty zůstanou v historii a nezvýší plánované kredity.');return {kind:'legacy',courses,enrollments:[],placements,notes:[...new Set(notes)],source:'Plán z V1'}
}
export function mergeImport(s:StudyState,p:ImportPreview):StudyState {if(p.backup)return p.backup;const next=structuredClone(s);for(const c of p.courses){const i=next.courses.findIndex(x=>x.code===c.code);if(i<0)next.courses.push(c);else if(p.kind==='legacy')next.courses[i]={...next.courses[i],...c};else next.courses[i]={...next.courses[i],name:c.name,credits:c.credits}}
 if(p.kind==='results')next.enrollments=[]
 for(const e of p.enrollments){const i=next.enrollments.findIndex(x=>x.id===e.id);if(i<0)next.enrollments.push(e);else next.enrollments[i]=e}if(p.official)next.official=p.official
 if(p.placements){const plan=next.plans.find(p=>p.id===next.activePlanId)!;plan.placements={...plan.placements,...p.placements}}
 if(p.kind==='results')for(const plan of next.plans)for(const e of p.enrollments.filter(e=>e.semester==='B261'&&!isPassed(e)))if(!(e.code in plan.placements))plan.placements[e.code]='B261'
 if(p.kind==='results'&&p.official?.credits!==null&&p.official?.credits!==undefined&&earnedCredits(next)!==p.official.credits)throw new Error('Výsledný počet kreditů neodpovídá výpisu.')
 next.updatedAt=new Date().toISOString();validateState(next);return next}
export function previewCredits(p:ImportPreview){if(p.backup)return earnedCredits(p.backup);const map=new Map<string,number>();p.enrollments.filter(isPassed).forEach(e=>map.set(e.code,e.credits));return [...map.values()].reduce((n,c)=>n+c,0)}
