export type Role = 'P' | 'PV' | 'V'
export type Season = 'winter' | 'summer' | 'both' | 'unknown'
export type Group = 'core' | 'thesis' | 'english' | 'electiveCore' | 'programming' | 'introduction' | 'other'
export interface Course {code:string;name:string;credits:number;role:Role;season:Season;group:Group;lectures:number;practices:number;labs:number;selfStudy:number|null;hoursKnown?:boolean;range?:string;kosLink:string;surveyLink:string;note?:string}
export interface Enrollment {id:string;code:string;semester:string;credits:number;role:Role;completion:string;assessment:string;grade:string;date:string;teacher:string;source:string}
export interface Plan {id:string;name:string;placements:Record<string,string|null>}
export interface StudyState {schemaVersion:2;courses:Course[];enrollments:Enrollment[];plans:Plan[];activePlanId:string;settings:{name:string;workHours:number;weekBudget:number;lessonMinutes:number;targetCredits:number;confirmedProgramme:boolean};official:{credits:number|null;average:number|null;weightedAverage:number|null;importedAt:string|null;source:string};updatedAt:string}
export const SEMESTERS = [{id:'B261',name:'Zima 2026/27',short:'Zima 2026',index:5,season:'winter'},{id:'B262',name:'Léto 2026/27',short:'Léto 2027',index:6,season:'summer'},{id:'B271',name:'Zima 2027/28',short:'Zima 2027',index:7,season:'winter'},{id:'B272',name:'Léto 2027/28',short:'Léto 2028',index:8,season:'summer'}]
export const GROUPS: {id:Group;name:string;credits:number;count:number}[]=[{id:'core',name:'Povinné předměty',credits:126,count:25},{id:'electiveCore',name:'Odborné povinně volitelné',credits:14,count:3},{id:'programming',name:'Programování',credits:6,count:1},{id:'introduction',name:'Úvod do inženýrství',credits:4,count:1},{id:'english',name:'Angličtina',credits:0,count:2},{id:'thesis',name:'Bakalářská práce',credits:20,count:1}]
export const PLAN_URL='https://intranet.fel.cvut.cz/cz/education/bk/plany/pl30018325.html'
export function cleanCode(value:string){const v=value.trim();if(/^https?:/i.test(v)){try{const u=new URL(v);const code=u.pathname.match(/course-syllabus\/([^/]+)/i)?.[1];return code?decodeURIComponent(code).toUpperCase():v.toUpperCase()}catch{return v.toUpperCase()}}return v.toUpperCase()}
export function safeUrl(value:string){try{const u=new URL(value);return ['https:','http:'].includes(u.protocol)?u.href:''}catch{return ''}}
export const isPassed=(e:Enrollment)=>/^[ABCDE]$/.test(e.grade)||(['Z','KZ'].includes(e.completion)&&e.assessment==='Z'&&!e.grade)
export function completedCodes(s:StudyState){return new Set(s.enrollments.filter(isPassed).map(e=>e.code))}
export function successfulEnrollments(s:StudyState){const values=new Map<string,Enrollment>();[...s.enrollments].filter(isPassed).sort((a,b)=>a.semester.localeCompare(b.semester)||a.id.localeCompare(b.id)).forEach(e=>values.set(e.code,e));return values}
export function earnedCredits(s:StudyState){return [...successfulEnrollments(s).values()].reduce((n,e)=>n+e.credits,0)}
export function repeatingCodes(s:StudyState){const done=completedCodes(s);return new Set(s.enrollments.filter(e=>!done.has(e.code)&&(e.grade==='F'||e.assessment==='N')).map(e=>e.code))}
export const activePlan=(s:StudyState)=>s.plans.find(p=>p.id===s.activePlanId)||s.plans[0]
export function plannedCourses(s:StudyState,id?:string){const done=completedCodes(s);const p=activePlan(s);return s.courses.filter(c=>!done.has(c.code)&&p.placements[c.code]&&(id===undefined||p.placements[c.code]===id))}
export const plannedCredits=(s:StudyState)=>plannedCourses(s).reduce((n,c)=>n+c.credits,0)
export function groupProgress(s:StudyState){const done=completedCodes(s),planned=new Set(plannedCourses(s).map(c=>c.code));return GROUPS.map(g=>{const courses=s.courses.filter(c=>c.group===g.id);const passed=courses.filter(c=>done.has(c.code)),placed=courses.filter(c=>planned.has(c.code));return {...g,earned:passed.reduce((n,c)=>n+(successfulEnrollments(s).get(c.code)?.credits||0),0),passedCount:passed.length,planned:placed.reduce((n,c)=>n+c.credits,0),plannedCount:placed.length}})}
export function workload(s:StudyState,id:string){const cs=plannedCourses(s,id);const lessons=cs.reduce((n,c)=>n+c.lectures+c.practices+c.labs,0);const self=cs.reduce((n,c)=>n+(c.selfStudy||0),0);const unknown=cs.filter(c=>c.selfStudy===null).length;const school=lessons*s.settings.lessonMinutes/60;return {lessons,school,self,unknown,unknownContact:cs.filter(c=>c.hoursKnown===false).length,total:school+self+s.settings.workHours}}
export function moveWarnings(s:StudyState,code:string,target:string|null){const c=s.courses.find(c=>c.code===code),sem=SEMESTERS.find(v=>v.id===target);if(!c||!sem)return [];const w:string[]=[];if(c.season!=='both'&&c.season!=='unknown'&&c.season!==sem.season)w.push(`Podle katalogu se ${c.name} obvykle vyučuje jen ${c.season==='winter'?'v zimě':'v létě'}. Ověř vypsání v KOSu.`);if(c.season==='unknown')w.push('Období výuky není známé. Ověř vypsání v KOSu.');if(sem.id==='B272'&&c.group!=='thesis')w.push('Poslední semestr chceš nechat pro bakalářku a státnice. Tento předmět do něj přidá další zátěž.');if(s.enrollments.some(e=>e.code===code&&e.semester==='B261')&&target!=='B261')w.push('Předmět je zapsaný v KOSu v zimě 2026/27. Přesun mění pouze tento plán, zápis v KOSu zůstává.');const ps={...s,plans:s.plans.map(p=>p.id===s.activePlanId?{...p,placements:{...p.placements,[code]:target}}:p)};const load=workload(ps,target!);if(load.total>s.settings.weekBudget)w.push(`Známá zátěž včetně práce je ${Math.round(load.total)} h týdně, nad rozpočtem ${s.settings.weekBudget} h.`);return w}
export function planWarnings(s:StudyState){const w:{code?:string;text:string}[]=[];for(const c of plannedCourses(s)){const sem=activePlan(s).placements[c.code];moveWarnings(s,c.code,sem).filter(x=>!x.startsWith('Známá')).forEach(text=>w.push({code:c.code,text}))}for(const sem of SEMESTERS){const load=workload(s,sem.id);if(load.total>s.settings.weekBudget)w.push({text:`${sem.name}: známá zátěž ${Math.round(load.total)} h je nad týdenním rozpočtem.`})}return w}
export function semesterLabel(id:string){const m=id.match(/^B(\d{2})([12])$/);if(!m)return id;const y=2000+Number(m[1]);return `${m[2]==='1'?'Zima':'Léto'} ${y}/${String(y+1).slice(2)}`}
export function validateState(value:unknown):StudyState {
 const s=value as StudyState;if(!s||s.schemaVersion!==2||!Array.isArray(s.courses)||!Array.isArray(s.enrollments)||!Array.isArray(s.plans)||!s.plans.length||!s.settings||!s.official)throw new Error('Tento soubor není platná záloha Semester V2.')
 if(s.courses.length>3000||s.enrollments.length>10000||s.plans.length>30)throw new Error('Soubor obsahuje příliš mnoho záznamů.')
 if(typeof s.settings.name!=='string'||!s.settings.name.trim()||s.settings.name.length>60||typeof s.settings.confirmedProgramme!=='boolean')throw new Error('Neplatný profil studia.');for(const k of ['credits','average','weightedAverage'] as const)if(s.official[k]!==null&&(!Number.isFinite(s.official[k])||s.official[k]!<0))throw new Error('Neplatný souhrn výsledků.');if(typeof s.official.source!=='string'||(s.official.importedAt!==null&&(typeof s.official.importedAt!=='string'||!Number.isFinite(Date.parse(s.official.importedAt)))))throw new Error('Neplatný zdroj výpisu.');const codes=new Set<string>();for(const c of s.courses){if(!c||typeof c.code!=='string'||!/^[A-Z0-9][A-Z0-9-]{1,29}$/.test(c.code)||codes.has(c.code)||typeof c.name!=='string'||!c.name.trim()||!['P','PV','V'].includes(c.role)||!['winter','summer','both','unknown'].includes(c.season)||![...GROUPS.map(g=>g.id),'other'].includes(c.group))throw new Error('Neplatný nebo duplicitní předmět v záloze.');codes.add(c.code);for(const k of ['credits','lectures','practices','labs'] as const)if(!Number.isFinite(c[k])||c[k]<0||c[k]>999)throw new Error('Neplatná číselná hodnota předmětu.');if(c.selfStudy!==null&&(!Number.isFinite(c.selfStudy)||c.selfStudy<0||c.selfStudy>168))throw new Error('Neplatný odhad samostudia.');c.kosLink=safeUrl(c.kosLink);c.surveyLink=safeUrl(c.surveyLink)}
 const ids=new Set<string>();for(const e of s.enrollments){if(!e||typeof e.id!=='string'||ids.has(e.id)||!codes.has(e.code)||!/^B\d{2}[12]$/.test(e.semester)||!Number.isFinite(e.credits)||e.credits<0||!['P','PV','V'].includes(e.role)||!['','A','B','C','D','E','F'].includes(e.grade)||!['','Z','N'].includes(e.assessment)||!['Z','KZ','ZK','Z,ZK'].includes(e.completion))throw new Error('Neplatný záznam studijního výsledku.');for(const k of ['date','teacher','source'] as const)if(typeof e[k]!=='string')throw new Error('Neplatné údaje výsledku.');ids.add(e.id)}
 const planIds=new Set<string>();for(const p of s.plans){if(!p||typeof p.id!=='string'||planIds.has(p.id)||typeof p.name!=='string'||!p.placements||typeof p.placements!=='object')throw new Error('Neplatná varianta plánu.');planIds.add(p.id);for(const [code,sem] of Object.entries(p.placements))if(!codes.has(code)||(sem!==null&&!SEMESTERS.some(t=>t.id===sem)))throw new Error('Neplatné zařazení předmětu.')}if(!planIds.has(s.activePlanId))throw new Error('Chybí aktivní plán.');for(const k of ['workHours','weekBudget','lessonMinutes','targetCredits'] as const)if(!Number.isFinite(s.settings[k])||s.settings[k]<0||s.settings[k]>(k==='targetCredits'?999:168))throw new Error('Neplatné nastavení studia.');if(!s.settings.weekBudget||!s.settings.lessonMinutes||!s.settings.targetCredits)throw new Error('Rozpočet, délka hodiny a cílové kredity musí být kladné.');return s
}
